py_binary(
    name = "binary_without_explicit_legacy_create_init",
    srcs = ["binary.py"],
    main = "binary.py",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "binary_setting_legacy_create_init",
    srcs = ["binary.py"],
    legacy_create_init = False,
    main = "binary.py",
    visibility = ["//visibility:public"],
)
